# Generated by Django 6.0.3 on 2026-03-22 11:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_discountcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('products', models.JSONField(default=dict, help_text='Produkty w zamówieniu w JSON')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('blik_code', models.CharField(blank=True, max_length=6, null=True)),
                ('status', models.CharField(choices=[('pending', 'Oczekiwanie na płatność'), ('paid', 'Opłacone'), ('cancelled', 'Anulowane')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='blog.discountcode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
